main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path("signup/",views.signup, name="signup"),
    path("login/",views.LoginView.as_view(),name="login"),
    path("home/",views.home, name="home"),
    path("create_quiz/",views.create_quiz, name="create_quiz"),
    path("create_question/<quiz_id>/", views.create_question, name= "create_question"),
    path("answer_quiz_list/",views.answer_quiz_list, name="answer_quiz_list"),
    path("answer_quiz/<quiz_id>/",views.answer_quiz,name="answer_quiz"),
    path("result/<quiz_id>/", views.result,name="result"),
    path("quiz_information/<quiz_id>", views.quiz_information, name="quiz_information"),
    path("logout/",views.LogoutView.as_view(), name="logout"),
]

quiz_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Quiz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # 作成者
    title = models.CharField(max_length=50) # タイトル
    description = models.TextField(max_length=500) # 説明文

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE) # どのクイズに対する質問か
    question = models.CharField(max_length=100) # 質問文

    def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # どの質問に対する選択肢か
    choice = models.CharField(max_length=200) # 選択肢
    is_answer = models.BooleanField(default=False) # 正解かどうか

    def __str__(self):
        return self.choice
    
class QuizAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    answered_at = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)
    answer_rate = models.FloatField(default=0)

    def __str__(self):
        return f"{self.user}_{self.quiz}"
    
class QuizInformation(models.Model):
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    average_score=models.FloatField(default=0)
    answer_rate = models.FloatField(default=0)
    

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User,Quiz, Question, Choice



class SignUpForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["username"].widget.attrs["class"] ="form-control"
        self.fields["email"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["class"] = "form-control"
#下のやつはテーブルのメタ情報#
    class Meta:
        model = User
        fields = ("username","email")

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["password"].widget.attrs["class"] = "form-control"
        
class QuizForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["rows"] = "3"
        
    class Meta:
        model = Quiz
        fields = ("title", "description")

class QuestionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields["question"].widget.attrs["class"] = "form-control"

    class Meta:
        model = Question
        fields = ("question",)

class ChoiceForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["choice"].widget.attrs["class"]  = "form-control"       

    class Meta:
        model = Choice
        fields = ("choice",)

main/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import auth
from django.contrib.auth import views as auth_views
from .forms import LoginForm, SignUpForm,QuizForm,QuestionForm,ChoiceForm
from django.contrib.auth.decorators import login_required
from .models import Quiz, Choice,QuizAnswer,QuizInformation
from django.db.models import Avg,Q
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
def index(request):
    return render(request,"main/index.html")

def signup(request):
    if request.method == "GET":
        form = SignUpForm()
    elif request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]#何故？#
            user = auth.authenticate(username=username,password=password)
            if user:
                auth.login(request, user)
            
            return redirect("index")
    context = {"form": form}
    return render(request,"main/signup.html",context)

class LoginView(auth_views.LoginView):
    authentication_form = LoginForm
    template_name= "main/login.html"

@login_required
def home(request):
    user = request.user
    quiz_list = Quiz.objects.filter(user=user)
    context = {
        "quiz_list":quiz_list,
    }
    return render(request, "main/home.html",context)


@login_required
def create_quiz(request):
    if request.method == "GET":
        quiz_form = QuizForm()
    elif request.method == "POST":
        quiz_form = QuizForm(request.POST)
        if quiz_form.is_valid():
            quiz = quiz_form.save(commit=False)
            user = request.user
            quiz.user = user
            #ここでquiz.user=request.userにしてもダメなのか#
            quiz.save()
            return redirect("create_question", quiz.id)
    context = {
        "quiz_form":quiz_form,
    }
    return render(request, "main/create_quiz.html", context)
    
@login_required
def create_question(request,quiz_id):

    quiz = get_object_or_404(Quiz, id=quiz_id)

    current_question_num = quiz.question_set.all().count()
    next_question_num = current_question_num + 1
    if request.method == "GET":
        question_form = QuestionForm()
        choice_form = ChoiceForm()
    
    elif request.method == "POST":
        question_form = QuestionForm(request.POST)
        choice_form = ChoiceForm()
        choices = request.POST.getlist("choice")
        answer_choice_num = request.POST["is_answer"]

        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.quiz = quiz
            question.save()

            for i ,choice in enumerate(choices):

                if i == int(answer_choice_num):
                    Choice.objects.create(
                        question=question, choice=choice, is_answer = True
                )
                else:
                    Choice.objects.create(
                        question=question, choice=choice, is_answer = False
                )
            return redirect("create_question",quiz_id)
        
        
    context= {
        "question_form": question_form,
        "choice_form": choice_form,
        "quiz_id" : quiz_id,
        "next_question_num" : next_question_num,
    }

    return render(request,"main/create_question.html", context)



@login_required
def answer_quiz_list(request):
    user = request.user
    quiz_list = Quiz.objects.exclude(user=user)
    keyword = request.GET.get('keyword')
    if keyword:
        keywords = keyword.split()
        for k in keywords:
            quiz_list = quiz_list.filter(Q(title__icontains=keyword) | Q(description__icontains=keyword))
    context = {
        "quiz_list":quiz_list
    }
    return render(request,"main/answer_quiz_list.html",context)


@login_required
def answer_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    questions = quiz.question_set.all()
    score = 0

    question_num = questions.count()
    user = request.user
    if request.method == "POST":
        for question in questions:
            choice_id = request.POST.get(str(question.id))
            choice_obj = get_object_or_404(Choice, id=choice_id)
            if choice_obj.is_answer:
                score += 1    
        answer_rate = score*100/question_num
        QuizAnswer.objects.create(
            user=user, quiz=quiz,score=score,answer_rate=answer_rate
        )
        # ユーザーが回答したクイズの情報を取得する
        quiz_answer = QuizAnswer.objects.filter(quiz=quiz)
        # 回答したクイズに対する全回答の平均得点の算出
        whole_average_score = quiz_answer.aggregate(Avg('score'))["score__avg"]
        # 回答したクイズに対する全回答の得点率の算出
        whole_answer_rate = quiz_answer.aggregate(Avg('answer_rate'))["answer_rate__avg"]

        # クイズ情報が存在すればユーザーが回答した分を含めて更新
        # 存在しなければ新しくクイズ情報を作成する
        QuizInformation.objects.update_or_create(
            quiz=quiz,
            defaults={
                "average_score":whole_average_score,
                "answer_rate":whole_answer_rate
            },
        )

        return redirect("result", quiz_id)
    context = {
        "quiz":quiz,
        "questions":questions,
    }
    return render(request, "main/answer_quiz.html",context)

@login_required
def quiz_information(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    quiz_information = QuizInformation.objects.filter(quiz=quiz).first()
    quiz_answer = quiz.quizanswer_set.all()
    context = {
        "quiz_answer":quiz_answer,
        "quiz_information":quiz_information,
    }
    return render(request, "main/quiz_information.html",context)



@login_required
def result(request,quiz_id):
    user = request.user
    quiz = get_object_or_404(Quiz, id=quiz_id)
    quiz_answer = QuizAnswer.objects.filter(quiz=quiz,user=user).order_by("answered_at").last()
    context = {
        "quiz_answer":quiz_answer,
    }

    return render(request, "main/result.html",context)

class LogoutView(auth_views.LogoutView,LoginRequiredMixin):
    pass

main/templates/main/answer_quiz.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="m-3">
    <form action="{% url 'answer_quiz' quiz.id %}" method="POST">
        {% csrf_token %}

        {% for question in questions %}
        <div class="card-body my-3">
            <h5 class="card-title">{{ forloop.counter }}.{{ question.question }}</h5>

            {% for choice in question.choice_set.all %}
            <div class="form-check">
                <input type="radio" name="{{ question.id }}" id="choice-{{ question.id }}-{{ choice.id }}" value="{{ choice.id }}" required> {# choice オブジェクトの id を送信する #}
                <label for="choice-{{ question.id }}-{{ choice.id }}">{{ choice.choice }}</label><br>
            </div>
            {% endfor %}

        </div>
        {% endfor %}

        <div class="col text-center">
            <button class="btn btn-secondary" type="submit">提出する</button>
        </div>

    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/answer_quiz_list.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="m-3">
    <form action="{% url 'answer_quiz_list' %}" method="GET">
        <div class="input-group">
            <input type="text" class="form-control" name="keyword">
            <button class="btn btn-secondary" type="submit">検索</button>
        </div>
    </form>

    {% for quiz in quiz_list %}
        {% if quiz.question_set.all %}
        <div class="my-3">
            <h5>{{quiz.title}}</h5>
            <p>{{quiz.description}}</p>
            <a href="{% url 'answer_quiz' quiz.id %}" class="btn btn-secondary">この問題を解く</a>
        </div>
        {% endif %}
    {% empty %}
        <p>解くことができるクイズは存在しません</p>
    {% endfor %}
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>QuizApp</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% block extra_style %}{% endblock %}
    </head>
    <body>
        {% block header %}
        {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">QuizApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{% url 'answer_quiz_list' %}" tabindex="-1">クイズを解く</a>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button style="border: none; background: transparent;" type="submit" aria-current="page" class="nav-link active">ログアウト</a>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
        {% endif %}
        {% endblock %}
        {% block content %}{% endblock %}
        {% block footer %}{% endblock %}
    </body>
</html>

main/templates/main/create_question.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div class="m-3">
    <form action="{% url 'create_question' quiz_id %}" method="POST">
        {% csrf_token %}
        <h1>第{{next_question_num}}問目</h1>
        <label for="{{question_form.question.label}}">問題</label>
        {{ question_form.question }}
        <div class="mt-2">
            <label for="{{choice_form.choice.label}}">選択肢1</label>
            {{ choice_form.choice }}
            <input type="radio" id="0" name="is_answer" value=0 required>
            <label for="0">正解</label><br>
        </div>

        <div class="mt-2">
            <label for="{{choice_form.choice.label}}">選択肢2</label>
            {{ choice_form.choice }}
            <input type="radio" id="1" name="is_answer" value=1 required>
            <label for="1">正解</label><br>
        </div>

        <div class="mt-2">
            <label for="{{choice_form.choice.label}}">選択肢3</label>
            {{ choice_form.choice }}
            <input type="radio" id="2" name="is_answer" value=2 required>
            <label for="2">正解</label><br>
        </div>

        <div class="mt-2">
            <label for="{{choice_form.choice.label}}">選択肢4</label>
            {{ choice_form.choice }}
            <input type="radio" id="3" name="is_answer" value=3 required>
            <label for="3">正解</label><br>
        </div>

        <div class="mx-auto mt-3" style="width: 200px;">
            <div class='btn-toolbar' role="toolbar">
                <div>
                    {% if next_question_num != 1 %}
                        <a href="{% url 'home' %}" class="btn btn-secondary">完了する</a>
                    {% endif %}
                    <button class="btn btn-secondary" type="submit">追加する</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/create_quiz.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div class="m-3">
    <form action="{% url 'create_quiz' %}" method="POST">
        {% csrf_token %}
        <label for="{{quiz_form.title.label}}">クイズ名</label>
        {{ quiz_form.title }}
        <div class="form-group mt-3">
            <label for="{{quiz_form.description.label}}">クイズの説明</label>
            {{ quiz_form.description }}
        </div>
        <div class="col text-center mt-2">
            <button class="btn btn-secondary" type="submit">追加する</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="m-3">
    <div class="d-grid gap-2">
        <a href="{% url 'create_quiz' %}" class="btn btn-secondary" type="button">問題を作成する</a>
    </div>
        {% for quiz in quiz_list %}
        <div class="card-body my-3">
            <h5 class="card-title mb-2">{{ quiz.title }}</h5>
            <a href="{% url 'quiz_information' quiz.id %}" class="btn btn-secondary">問題の詳細</a>
        </div>
        {% endfor %}
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center" style="height:100vh;">
    <a href="{% url 'login'%}" class="btn btn-secondary mx-2">ログイン</a>
    <a href="{% url 'signup' %}" class="btn btn-secondary">会員登録</a>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block header_title %}ログイン{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center" style="height:100vh;">
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        {% if form.errors %}
        <div>ユーザー名とパスワードが一致しません。</div>
        {% endif %}
        <div class="mb-2">
            <label class="form-label" for="{{ form.username.id_for_label }}">ユーザー名</label>
            {{ form.username }}
        </div>
        <div class="mb-2">
            <label class="form-label" for="{{ form.password.id_for_label }}">パスワード</label>
            {{ form.password }}
        </div>
        <div class="col text-center mt-2">
            <button class="btn btn-secondary" type="submit">送信</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/quiz_information.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="m-3">
    {% if quiz_information %}
        <h1>{{quiz_information.quiz}}の結果</h1>
        <p>回答数：{{quiz_answer|length}}</p>
        <p>平均得点：{{quiz_information.average_score|floatformat:2}}点</p>
        <p>得点率：{{quiz_information.answer_rate|floatformat:2}}%</p>
        <p></p>
        <div class="col text-center">
            <a href="{% url 'home' %}" class="btn btn-secondary" type="button">クイズ一覧に戻る</a>
        </div>
    {% else %}
        <p>クイズの情報はありません</p>
    {% endif %}
</div>
{% endblock %}

{% block footer %}{% endblock %}


{% comment %}
quiz_informationはクイズを作ったユーザーが見れると言うものらしい
{% endcomment %}

main/templates/main/result.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="m-3">
    <h1>結果</h1>
    <p>得点 : {{ quiz_answer.score }}点</p>
    <p>得点率 : {{quiz_answer.answer_rate }}%</p>
    <div class="col text-center">
        <a href="{% url 'answer_quiz_list' %}" class="btn btn-secondary" type="button">クイズ一覧に戻る</a>
    </div>
</div>
{% endblock %}

{% block footer %}{% endblock %}

main/templates/main/signup.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center" style="height:100vh;">
    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label class="form-label" for="{{ form.username.id_for_label }}">ユーザー名</label>
            {{ form.username }}
        </div>
        <div class="mb-2">
            <label class="form-label" for="{{ form.username.id_for_label }}">メールアドレス</label>
            {{ form.email }}
        </div>
        <div class="mb-2">
            <label class="form-label" for="{{ form.password1.id_for_label }}">パスワード</label>
            {{ form.password1 }}
        </div>
        <div class="mb-2">
            <label class="form-label" for="{{ form.password2.id_for_label }}">パスワード(確認用)</label>
            {{ form.password2 }}
        </div>
        <div class="col text-center mt-2">
            <button class="btn btn-secondary" type="submit">送信</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}